#!/bin/bash
cd /home/amahiworld/.awupdater
current=$(cat "current")
MS=$(curl https://raw.githubusercontent.com/amahi/irc-bot/master/Installer/Refs/ref)
if [ "$current" == "$MS" ]
then
echo "No Updates Found"
fi
if [ "$current" -lt "$MS" ]
then
cd /home/amahiworld
pkill supybot
rm -rf *.conf*
rm -rf backup
rm -rf conf
rm -rf data
rm -rf logs
rm -rf *.sh
rm -rf plugins
rm -rf web
rm -rf tmp
wget https://raw.githubusercontent.com/amahi/irc-bot/master/Files/Releases/MS$MS/AmahiWorld_MS$MS.tar
tar xvf AmahiWorld_MS$MS.tar
rm -rf AmahiWorld_MS$MS.tar
cd AmahiWorld
mv * ../
cd ..
rm -rf AmahiWorld
./startbot.sh
cd .awupdater
rm -rf current
echo "$MS" > current
./startbot.sh
fi